In [5]:
import tensorflow as tf
from tensorflow.keras import layers 

In [4]:
x = tf.random.normal([2,5,5,3])
w = tf.random.normal([3,3,3,4])
#out = tf.nn.conv2d(x, w, strides=1, padding=[[0,0], [0,0], [0,0], [0,0]])
out = tf.nn.conv2d(x, w, strides=1, padding="SAME")
out

<tf.Tensor: id=37, shape=(2, 5, 5, 4), dtype=float32, numpy=
array([[[[ 3.3662224e+00, -5.3032106e-01, -1.7471175e-01,
          -4.7011297e-02],
         [-2.9569719e+00,  4.8868942e-01,  4.5153701e-01,
          -3.1303778e-01],
         [-3.9436990e-01,  9.0322202e-01,  5.4109507e+00,
          -3.1245413e+00],
         [-1.2574404e-01,  1.1612398e+01, -7.5926270e+00,
           1.7782741e+00],
         [-1.6322324e+00,  3.2179055e+00,  1.0533234e+00,
           7.4468255e-01]],

        [[-1.1285009e+00,  3.8506031e-01,  6.9780707e-01,
          -1.7934863e-01],
         [ 1.4109246e+00,  5.1424160e+00,  5.7643809e+00,
          -2.7473288e+00],
         [-1.0350244e+00,  1.8408554e+00, -3.0038168e+00,
           3.1779838e+00],
         [-5.3627425e-01, -3.0086482e+00,  1.4890067e+01,
          -1.0334661e+01],
         [ 3.2216578e+00,  5.6095653e+00, -2.5125918e+00,
           2.7547545e+00]],

        [[ 1.0089080e+01,  5.4906850e+00,  6.1598072e+00,
           3.1524692e+00],


In [7]:
layer = layers.Conv2D(4, kernel_size=3, strides=1, padding='SAME')
out = layer(x)
out.shape

TensorShape([2, 5, 5, 4])

In [8]:
layer.trainable_variables

[<tf.Variable 'conv2d_1/kernel:0' shape=(3, 3, 3, 4) dtype=float32, numpy=
 array([[[[-0.11258753,  0.27679643, -0.09449877, -0.05464983],
          [ 0.05248091,  0.16253307, -0.2434994 , -0.05351841],
          [-0.00833243, -0.17961265, -0.30737004, -0.05683205]],
 
         [[-0.25093675,  0.04644018,  0.07669666,  0.03699532],
          [-0.28597322,  0.05413029, -0.26796475, -0.01933965],
          [-0.24979189, -0.14229256, -0.17666145, -0.17195514]],
 
         [[ 0.01704666,  0.16263145, -0.26680422,  0.03763869],
          [-0.30768487, -0.09400646,  0.1795888 ,  0.18169966],
          [-0.13874228,  0.08187199, -0.02233925,  0.18146122]]],
 
 
        [[[ 0.08883625, -0.10652554, -0.13505782,  0.04769388],
          [-0.12398402,  0.12104866,  0.1671313 ,  0.25891206],
          [ 0.19182172, -0.0230768 ,  0.30298975, -0.2351938 ]],
 
         [[-0.23928457, -0.0355908 , -0.29596308, -0.25799727],
          [-0.30673063,  0.20056263,  0.2763445 , -0.17225885],
          [-0.

In [9]:
x = tf.range(25) + 1

In [11]:
x = tf.reshape(x, [1, 5, 5, 1])
x = tf.cast(x, tf.float32)

In [26]:
w = tf.constant([[-1,2,-3.], [4, -5, 6], [-7,8,-9]])
w = tf.expand_dims(w, axis=2)
w = tf.expand_dims(w, axis=3)
w.shape

TensorShape([3, 3, 1, 1])

In [29]:
out = tf.nn.conv2d(x, w, strides=2, padding='VALID')
out

<tf.Tensor: id=138, shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[ -67.],
         [ -77.]],

        [[-117.],
         [-127.]]]], dtype=float32)>

In [30]:
xx = tf.nn.conv2d_transpose(out, w, strides=2, padding='VALID', output_shape=[1,5,5,1])
xx

<tf.Tensor: id=140, shape=(1, 5, 5, 1), dtype=float32, numpy=
array([[[[   67.],
         [ -134.],
         [  278.],
         [ -154.],
         [  231.]],

        [[ -268.],
         [  335.],
         [ -710.],
         [  385.],
         [ -462.]],

        [[  586.],
         [ -770.],
         [ 1620.],
         [ -870.],
         [ 1074.]],

        [[ -468.],
         [  585.],
         [-1210.],
         [  635.],
         [ -762.]],

        [[  819.],
         [ -936.],
         [ 1942.],
         [-1016.],
         [ 1143.]]]], dtype=float32)>