In [2]:
import tensorflow as tf
from tensorflow.keras import layers

In [3]:
x = tf.range(10)
x = tf.random.shuffle(x)
x

<tf.Tensor: id=8, shape=(10,), dtype=int32, numpy=array([4, 9, 2, 6, 7, 1, 0, 8, 3, 5])>

In [7]:
net = layers.Embedding(10, 4)
out = net(x)
net.embeddings

<tf.Variable 'embedding_2/embeddings:0' shape=(10, 4) dtype=float32, numpy=
array([[-0.00156176, -0.0338545 ,  0.03610596, -0.02089578],
       [ 0.04053657, -0.0355368 , -0.02846841,  0.04887268],
       [ 0.0008484 , -0.03601378, -0.03946296,  0.01723893],
       [ 0.03755841, -0.0130744 ,  0.02156893,  0.04451224],
       [-0.01210865, -0.02391648,  0.01838031, -0.02554902],
       [-0.02189542, -0.02193762,  0.04263674,  0.0294688 ],
       [-0.01049458, -0.00949696, -0.04322711, -0.03019979],
       [-0.02689729,  0.02321018, -0.01697353,  0.02991791],
       [-0.009023  ,  0.00378064, -0.01650039,  0.00265337],
       [-0.03864832, -0.00298167,  0.04094818,  0.03324611]],
      dtype=float32)>

In [8]:
cell = layers.SimpleRNNCell(3)
cell.build(input_shape=(None, 4))
cell.trainable_variables

[<tf.Variable 'kernel:0' shape=(4, 3) dtype=float32, numpy=
 array([[ 0.6511543 , -0.6071284 ,  0.5307218 ],
        [ 0.2724104 , -0.7232544 , -0.3792742 ],
        [ 0.45291352, -0.7770123 , -0.1623295 ],
        [-0.37824273,  0.25198245, -0.17569488]], dtype=float32)>,
 <tf.Variable 'recurrent_kernel:0' shape=(3, 3) dtype=float32, numpy=
 array([[-0.12261713, -0.9874527 , -0.09950946],
        [-0.98703   ,  0.13180089, -0.09165207],
        [ 0.10361752,  0.08698072, -0.99080664]], dtype=float32)>,
 <tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]

In [10]:
w = tf.ones([2,2])
eigenvalues = tf.linalg.eigh(w)[0]
eigenvalues

<tf.Tensor: id=106, shape=(2,), dtype=float32, numpy=array([0.       , 1.9999999], dtype=float32)>

In [12]:
val = [w]
for i in range(10):
    val.append([val[-1]@w])
print(val)

[<tf.Tensor: id=105, shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>, [<tf.Tensor: id=127, shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>], [<tf.Tensor: id=129, shape=(1, 2, 2), dtype=float32, numpy=
array([[[4., 4.],
        [4., 4.]]], dtype=float32)>], [<tf.Tensor: id=131, shape=(1, 1, 2, 2), dtype=float32, numpy=
array([[[[8., 8.],
         [8., 8.]]]], dtype=float32)>], [<tf.Tensor: id=133, shape=(1, 1, 1, 2, 2), dtype=float32, numpy=
array([[[[[16., 16.],
          [16., 16.]]]]], dtype=float32)>], [<tf.Tensor: id=135, shape=(1, 1, 1, 1, 2, 2), dtype=float32, numpy=
array([[[[[[32., 32.],
           [32., 32.]]]]]], dtype=float32)>], [<tf.Tensor: id=137, shape=(1, 1, 1, 1, 1, 2, 2), dtype=float32, numpy=
array([[[[[[[64., 64.],
            [64., 64.]]]]]]], dtype=float32)>], [<tf.Tensor: id=139, shape=(1, 1, 1, 1, 1, 1, 2, 2), dtype=float32, numpy=
array([[[[[[[[128., 128.],
             [128., 128.]]]

In [15]:
a = tf.random.uniform([2,2])
tf.clip_by_value(a, 0.4, 0.6)

<tf.Tensor: id=174, shape=(2, 2), dtype=float32, numpy=
array([[0.6, 0.6],
       [0.4, 0.4]], dtype=float32)>

In [1]:
a = tf.random.uniform([2,2])*5
b = tf.clip_by_norm(a, 5)
tf.norm(a), tf.norm(b)

NameError: name 'tf' is not defined

In [ ]:
w1 = tf.random.normal([3,3])
w2 = tf.random.normal([3,3])
global_norm = tf.math.sqrt(tf.norm(w1)**2 + tf.norm(w2)**2)
(ww1, ww2), global_norm = tf.clip_by_global_norm([w1, w2], 2)