In [2]:
import tensorflow as tf

In [2]:
a = 1.2
aa = tf.constant(1.2)
type(a), type(aa), tf.is_tensor(aa)

(float, tensorflow.python.framework.ops.EagerTensor, True)

In [4]:
x = tf.constant([1,2., 3.3])
x

<tf.Tensor: id=2, shape=(3,), dtype=float32, numpy=array([1. , 2. , 3.3], dtype=float32)>

In [5]:
x.numpy()

array([1. , 2. , 3.3], dtype=float32)

In [6]:
tf.convert_to_tensor([1,2.])

<tf.Tensor: id=3, shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [7]:
import numpy as np

In [8]:
tf.convert_to_tensor(np.array([[1,2.],[3,4]]))

<tf.Tensor: id=4, shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>

In [9]:
tf.zeros([2,2])

<tf.Tensor: id=7, shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [10]:
tf.fill([2,2], -4)

<tf.Tensor: id=10, shape=(2, 2), dtype=int32, numpy=
array([[-4, -4],
       [-4, -4]])>

In [11]:
tf.random.normal([2,2])

<tf.Tensor: id=16, shape=(2, 2), dtype=float32, numpy=
array([[-1.9428034 ,  0.10992524],
       [-0.533335  ,  0.75961393]], dtype=float32)>

In [12]:
tf.range(10)

<tf.Tensor: id=20, shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [3]:
out = tf.random.uniform([4, 10])
out

<tf.Tensor: id=6, shape=(4, 10), dtype=float32, numpy=
array([[0.19980228, 0.36047518, 0.22682273, 0.7573906 , 0.7826865 ,
        0.79548323, 0.30156898, 0.22338724, 0.84905183, 0.32532823],
       [0.561543  , 0.21554017, 0.9381261 , 0.51011765, 0.5966393 ,
        0.43738914, 0.310534  , 0.398718  , 0.39303398, 0.8811636 ],
       [0.29724634, 0.2077136 , 0.06701231, 0.47179055, 0.8843044 ,
        0.19976151, 0.72707963, 0.4208665 , 0.44808722, 0.61702037],
       [0.62155664, 0.10921299, 0.6220473 , 0.56392884, 0.83640456,
        0.9413701 , 0.10995865, 0.94621444, 0.5380647 , 0.9816295 ]],
      dtype=float32)>

In [5]:
y = tf.constant([2,3,2,0])
y = tf.one_hot(y, depth=10)
loss = tf.keras.losses.mse(y, out)
loss = tf.reduce_mean(loss)
loss

<tf.Tensor: id=21, shape=(), dtype=float32, numpy=0.3677461>

In [6]:
x = tf.random.normal([4,32,32,3])

In [7]:
x[0]

<tf.Tensor: id=31, shape=(32, 32, 3), dtype=float32, numpy=
array([[[ 9.34707403e-01, -4.22675639e-01, -6.53365076e-01],
        [-9.67684686e-01,  2.05109328e-01, -1.37836197e-02],
        [-1.49418607e-01,  4.58021820e-01,  1.41177642e+00],
        ...,
        [ 7.68268943e-01,  1.28941488e+00,  4.23195720e-01],
        [-5.48075914e-01,  2.04409623e+00, -3.64151686e-01],
        [ 2.21794462e+00,  6.75474852e-02, -2.08276296e+00]],

       [[ 8.23147237e-01,  1.90998614e-01,  7.15829670e-01],
        [ 7.78648496e-01, -4.90416706e-01,  3.96285146e-01],
        [-7.57724285e-01, -3.21088016e-01, -1.28067124e+00],
        ...,
        [-9.01316226e-01, -6.73374951e-01, -4.59628165e-01],
        [ 7.66517341e-01, -7.54694700e-01, -4.91052389e-01],
        [ 8.83723617e-01, -1.31455600e+00,  1.03804492e-03]],

       [[ 4.86617118e-01,  6.55312359e-01,  1.23976600e+00],
        [-5.82791790e-02,  4.22616005e-02, -4.29520905e-01],
        [ 1.27580321e+00, -1.64918911e+00, -5.74611425e-

In [11]:
x = tf.range(96)

In [13]:
yx = tf.reshape(x, [2,4,4,3])

In [24]:
x = tf.random.uniform([28,28],maxval=10, dtype=tf.int32)

In [25]:
x = tf.expand_dims(x,axis=-1)
x.shape

TensorShape([28, 28, 1])

In [31]:
b = tf.constant([1,2])
b = tf.expand_dims(b, axis=0)
b = tf.tile(b, multiples=[3,1])
b

<tf.Tensor: id=113, shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [1, 2],
       [1, 2]])>

In [32]:
a = tf.random.normal([4,3,23,32])
b = tf.random.normal([4,3,32,2])
a@b

<tf.Tensor: id=126, shape=(4, 3, 23, 2), dtype=float32, numpy=
array([[[[ 4.9726086e+00,  3.9757485e+00],
         [ 6.0449753e+00,  6.3134098e-01],
         [-1.0388550e+01, -1.1317227e+00],
         [ 1.7564588e+00,  1.3352507e+01],
         [-1.3601943e+01,  3.7797203e+00],
         [ 1.7654285e+00,  3.3400526e+00],
         [-2.3828554e-01,  3.6461701e+00],
         [ 6.9503903e+00, -3.1810091e+00],
         [ 6.3499236e+00,  6.4835721e-01],
         [-2.3947885e+00,  6.6318307e+00],
         [-5.5911932e+00,  9.1187716e-02],
         [-7.3855000e+00,  3.5913987e+00],
         [ 1.7275703e+00, -7.6514797e+00],
         [ 7.5248396e-01, -1.9214181e+00],
         [-7.0400352e+00, -4.7025399e+00],
         [-9.0133309e-01, -9.1182976e+00],
         [-2.7789416e+00, -5.6738667e+00],
         [-1.8378304e+00, -4.0372829e+00],
         [-1.0927899e+00,  6.9241881e+00],
         [ 8.1597030e-01, -6.1935997e-01],
         [-9.0265036e+00, -3.4503906e+00],
         [ 4.7540469e+00, -2.45160