In [1]:
import tensorflow as tf

In [2]:
a = 1.2
aa = tf.constant(1.2)
type(a), type(aa), tf.is_tensor(aa)

(float, tensorflow.python.framework.ops.EagerTensor, True)

In [4]:
x = tf.constant([1,2., 3.3])
x

<tf.Tensor: id=2, shape=(3,), dtype=float32, numpy=array([1. , 2. , 3.3], dtype=float32)>

In [5]:
x.numpy()

array([1. , 2. , 3.3], dtype=float32)

In [6]:
tf.convert_to_tensor([1,2.])

<tf.Tensor: id=3, shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [7]:
import numpy as np

In [8]:
tf.convert_to_tensor(np.array([[1,2.],[3,4]]))

<tf.Tensor: id=4, shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>

In [9]:
tf.zeros([2,2])

<tf.Tensor: id=7, shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [10]:
tf.fill([2,2], -4)

<tf.Tensor: id=10, shape=(2, 2), dtype=int32, numpy=
array([[-4, -4],
       [-4, -4]])>

In [11]:
tf.random.normal([2,2])

<tf.Tensor: id=16, shape=(2, 2), dtype=float32, numpy=
array([[-1.9428034 ,  0.10992524],
       [-0.533335  ,  0.75961393]], dtype=float32)>

In [12]:
tf.range(10)

<tf.Tensor: id=20, shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>