In [17]:
import tensorflow as tf
import numpy as np

In [5]:
a = tf.reshape(tf.range(8), (2,4))
b = tf.reshape(tf.range(12),(3,4))
tf.concat([a,b], axis=0)

<tf.Tensor: id=37, shape=(5, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

In [10]:
a = tf.reshape(tf.range(8), (2,4))
b = tf.reshape(tf.range(8, 16),(2,4))
tf.stack([a,b], axis=1)

<tf.Tensor: id=88, shape=(2, 2, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])>

In [12]:
x = tf.reshape(tf.range(10*2*2), [10,2,2])
result = tf.split(x, axis=0, num_or_size_splits=10)
result

[<tf.Tensor: id=115, shape=(1, 2, 2), dtype=int32, numpy=
 array([[[0, 1],
         [2, 3]]])>, <tf.Tensor: id=116, shape=(1, 2, 2), dtype=int32, numpy=
 array([[[4, 5],
         [6, 7]]])>, <tf.Tensor: id=117, shape=(1, 2, 2), dtype=int32, numpy=
 array([[[ 8,  9],
         [10, 11]]])>, <tf.Tensor: id=118, shape=(1, 2, 2), dtype=int32, numpy=
 array([[[12, 13],
         [14, 15]]])>, <tf.Tensor: id=119, shape=(1, 2, 2), dtype=int32, numpy=
 array([[[16, 17],
         [18, 19]]])>, <tf.Tensor: id=120, shape=(1, 2, 2), dtype=int32, numpy=
 array([[[20, 21],
         [22, 23]]])>, <tf.Tensor: id=121, shape=(1, 2, 2), dtype=int32, numpy=
 array([[[24, 25],
         [26, 27]]])>, <tf.Tensor: id=122, shape=(1, 2, 2), dtype=int32, numpy=
 array([[[28, 29],
         [30, 31]]])>, <tf.Tensor: id=123, shape=(1, 2, 2), dtype=int32, numpy=
 array([[[32, 33],
         [34, 35]]])>, <tf.Tensor: id=124, shape=(1, 2, 2), dtype=int32, numpy=
 array([[[36, 37],
         [38, 39]]])>]

In [14]:
x = tf.ones((2,2))
tf.norm(x, ord=1)

<tf.Tensor: id=134, shape=(), dtype=float32, numpy=4.0>

In [15]:
tf.norm(x, ord=2)

<tf.Tensor: id=139, shape=(), dtype=float32, numpy=2.0>

In [19]:
tf.norm(x, ord=np.inf)

<tf.Tensor: id=147, shape=(), dtype=float32, numpy=1.0>

In [21]:
x = tf.random.normal((4,10))

In [22]:
tf.reduce_max(x, axis=1)

<tf.Tensor: id=163, shape=(4,), dtype=float32, numpy=array([1.776246 , 1.496614 , 1.9678279, 2.6379695], dtype=float32)>

In [23]:
tf.reduce_min(x, axis=1)

<tf.Tensor: id=165, shape=(4,), dtype=float32, numpy=array([-0.9494438 , -0.89463484, -1.1916949 , -2.043255  ], dtype=float32)>

In [24]:
tf.reduce_mean(x, axis=1)

<tf.Tensor: id=167, shape=(4,), dtype=float32, numpy=array([ 0.79449475, -0.01147981,  0.1863002 ,  0.48560008], dtype=float32)>

In [25]:
out = tf.random.normal((2,10))

In [26]:
out = tf.nn.softmax(out, axis=1)

In [27]:
out

<tf.Tensor: id=174, shape=(2, 10), dtype=float32, numpy=
array([[0.02358494, 0.0736087 , 0.06136298, 0.05354435, 0.1333368 ,
        0.16546926, 0.02432145, 0.01301941, 0.07881918, 0.372933  ],
       [0.03123041, 0.10523939, 0.06384347, 0.03767688, 0.06476178,
        0.41063854, 0.0054002 , 0.03094128, 0.04980941, 0.20045865]],
      dtype=float32)>

In [29]:
pred = tf.argmax(out, axis=1)
pred

<tf.Tensor: id=178, shape=(2,), dtype=int64, numpy=array([9, 5], dtype=int64)>

In [30]:
a = tf.constant([1,2,3,4,5,6])
b = tf.constant([7,8,1,6])
b = tf.pad(b, [[0,2]])
b

<tf.Tensor: id=182, shape=(6,), dtype=int32, numpy=array([7, 8, 1, 6, 0, 0])>

In [31]:
x = tf.range(9)
tf.minimum(x, 6)

<tf.Tensor: id=188, shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 6, 6])>

In [33]:
x = tf.random.uniform([4,35,8], maxval=100, dtype=tf.int32)

In [34]:
tf.gather(x, [0, 3,8, 11,12,26], axis=1)

<tf.Tensor: id=199, shape=(4, 6, 8), dtype=int32, numpy=
array([[[60, 39, 74, 23, 32, 77, 92, 98],
        [87, 13, 47, 47, 98, 30, 14, 36],
        [60, 46, 49, 72, 48, 84,  4,  0],
        [63, 50, 49, 14, 47,  2, 13, 56],
        [30, 88, 42, 89, 75,  9, 56, 75],
        [35, 13, 72, 92, 41,  6, 40, 15]],

       [[26, 44, 39, 42, 75,  1, 70, 25],
        [14, 54, 85, 77, 71, 13, 72, 98],
        [80,  8,  9, 95, 22, 10, 12, 23],
        [82, 38, 82, 81, 98, 33, 88, 74],
        [20, 73, 54, 61, 78, 64, 92, 66],
        [99, 79, 39, 85, 72, 82, 11, 51]],

       [[74,  2, 10, 59, 32, 16, 31,  1],
        [63, 77, 47, 24, 83, 40, 16, 85],
        [58, 70, 48, 38, 55, 10, 91, 22],
        [83, 98, 16,  1, 40, 16, 21, 43],
        [96, 46, 97, 94, 49, 48, 38, 53],
        [91, 60, 79, 31, 94,  7,  5,  5]],

       [[28, 77, 42, 73, 58, 65, 20, 81],
        [34, 90, 40, 15, 98, 84, 25, 82],
        [12, 39, 25, 88,  9, 40, 68, 47],
        [16, 63, 29, 49, 42, 56,  6, 26],
        [85, 

In [38]:
x = tf.random.uniform([2,3,8], maxval=100, dtype=tf.int32)

In [39]:
tf.gather_nd(x, [[0,0], [0,1], [1,1], [1,2]])

<tf.Tensor: id=251, shape=(4, 8), dtype=int32, numpy=
array([[22, 48, 23, 83, 93, 40, 37, 12],
       [91, 17, 82, 91,  4,  9, 13, 95],
       [23, 87, 21, 91, 21, 90, 94, 15],
       [81, 23, 82, 78, 86, 26, 84, 38]])>

In [40]:
x = tf.random.normal([3,3])
mask = x > 0
indices = tf.where(mask)
tf.gather_nd(x, indices)

<tf.Tensor: id=261, shape=(3,), dtype=float32, numpy=array([0.49213868, 2.241812  , 0.54398197], dtype=float32)>